### ISSUE TITLE
Add travis CI support

### ISSUE THREAD

**Issue by machow** [jonberliner/infiniteLibrary#3]
Hey, we've come this far--why not ;). I'll set it up next chance I get!

[travis ci](https://travis-ci.org/getting_started)

**Comment by machow** [comment]
Okay, I think since you're the owner of the repo, you'll need to enable travis-ci. You can log in to their page using your get hub, and then there should be a list of repos that you can activate.

**Comment by jonberliner** [comment]
A bit faded atm.  Will get to this on the morrow. Travis!  Why not!
